version: "3"
services:
  node:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    ports:
      - '5000:5000'
      - '8443:8443'
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ${data}:/data/db
